import React from 'react';
import Icon from '../../../components/AppIcon';
import Button from '../../../components/ui/Button';

const ErrorDisplay = ({ error, onRetry, onUploadAnother }) => {
  const getErrorIcon = (errorType) => {
    switch (errorType) {
      case 'network':
        return 'Wifi';
      case 'file':
        return 'FileX';
      case 'processing':
        return 'AlertTriangle';
      default:
        return 'XCircle';
    }
  };

  const getErrorTitle = (errorType) => {
    switch (errorType) {
      case 'network':
        return 'Network Error';
      case 'file':
        return 'Invalid File';
      case 'processing':
        return 'Processing Failed';
      default:
        return 'Upload Failed';
    }
  };

  const getErrorDescription = (errorType) => {
    switch (errorType) {
      case 'network':
        return 'Unable to connect to the server. Please check your internet connection and try again.';
      case 'file':
        return 'The selected file is not a valid XML file or is corrupted. Please select a valid Nmap XML file.';
      case 'processing':
        return 'An error occurred while processing your scan. The XML file may be malformed or contain unsupported data.';
      default:
        return 'An unexpected error occurred during the upload process. Please try again.';
    }
  };

  // Determine error type based on error message
  let errorType = 'general';
  if (error.includes('network') || error.includes('connection')) {
    errorType = 'network';
  } else if (error.includes('XML') || error.includes('file') || error.includes('format')) {
    errorType = 'file';
  } else if (error.includes('processing') || error.includes('parsing')) {
    errorType = 'processing';
  }

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="bg-card border border-error/20 rounded-lg p-6 shadow-elevation-1">
        <div className="text-center">
          <div className="flex items-center justify-center w-16 h-16 mx-auto bg-error/10 rounded-full mb-4">
            <Icon name={getErrorIcon(errorType)} size={32} className="text-error" />
          </div>
          
          <h3 className="text-lg font-semibold text-foreground mb-2">
            {getErrorTitle(errorType)}
          </h3>
          
          <p className="text-sm text-muted-foreground mb-4">
            {getErrorDescription(errorType)}
          </p>
          
          <div className="bg-error/5 border border-error/20 rounded-md p-3 mb-6">
            <p className="text-xs text-error font-mono">
              {error}
            </p>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-3">
          {errorType !== 'file' && (
            <Button 
              variant="default" 
              onClick={onRetry}
              className="flex-1"
              iconName="RotateCcw"
              iconPosition="left"
            >
              Try Again
            </Button>
          )}
          
          <Button 
            variant="outline" 
            onClick={onUploadAnother}
            className="flex-1"
            iconName="Upload"
            iconPosition="left"
          >
            Upload Different File
          </Button>
        </div>

        {errorType === 'file' && (
          <div className="mt-4 pt-4 border-t border-border">
            <div className="flex items-start space-x-3">
              <Icon name="Info" size={16} className="text-accent mt-0.5 flex-shrink-0" />
              <div className="text-xs text-muted-foreground">
                <p className="font-medium mb-1">Supported file requirements:</p>
                <ul className="space-y-1 list-disc list-inside ml-2">
                  <li>Valid XML format with proper structure</li>
                  <li>Generated by Nmap version 6.0 or higher</li>
                  <li>Contains host and port scan data</li>
                  <li>File size under 50MB</li>
                </ul>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ErrorDisplay;